import { NodebootOauth2StarterService } from './../nodeboot-oauth2-starter.service';
import { AfterViewInit, OnDestroy, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { BehaviorSubject, Subscription } from 'rxjs';
import { Resource } from '../nodeboot-oauth2-starter.service';
import * as i0 from "@angular/core";
export declare class OauthStarterApplicationResourceComponent implements OnInit, OnDestroy, AfterViewInit {
    private nbService;
    dialog: MatDialog;
    resources: Resource[];
    errorMessage: string | undefined;
    displayedColumns: string[];
    masterResources: string[];
    resultsLength: number;
    isLoadingResults: boolean;
    reload: BehaviorSubject<number>;
    userDataSubscription: Subscription;
    paginator: MatPaginator;
    sort: MatSort;
    constructor(nbService: NodebootOauth2StarterService, dialog: MatDialog);
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    ngOnInit(): void;
    openCreateAppResourceDialog(): void;
    openDeleteResourceDialog(resource: Resource): void;
    openOptionsDialog(resource: Resource): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<OauthStarterApplicationResourceComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<OauthStarterApplicationResourceComponent, "lib-oauth-starter-application-resource", never, {}, {}, never, never>;
}
